name: strapi on aws pipeline

on:
  push:
    branches: [develop]

  pull_request:
    branches: [develop]

env:
  APPLICATION_NAME: strapi-uat

jobs:
  build-and-deploy-strapi:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Build & Deploy Strapi
        run: |
          cd infrastructure \
           && corepack enable \
           && yarn install \
           && yarn cdk-uat deploy --require-approval never
